language: python
python: 2.7
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3 QA=true
matrix:
  include:
    - python: 2.6
      env: PLONE_VERSION=4.0
    - python: 2.6
      env: PLONE_VERSION=4.1
  allow_failures:
    - python: 2.6
      env: PLONE_VERSION=4.0
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - test "$PLONE_VERSION" = "4.0" -o "$PLONE_VERSION" = "4.1" && sed -ie "s#test, archetypes, dexterity#test, archetypes#" travis.cfg || true
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bin/test
  - test -v QA && bin/code-analysis || true
after_success: test -v QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
after_failure:
  - bin/buildout annotate -c travis.cfg
  - firefox -v
notifications:
  irc: irc.freenode.org#plonegovbr
